-- Workspace-wide assistant persistence budgets apply to every SQL writer.
-- Existing rows are preserved; oversized historical text may shrink.
CREATE TRIGGER assistant_insert_budget BEFORE INSERT ON assistants BEGIN
  SELECT RAISE(ABORT,'OPENFON_ASSISTANT_STORAGE_LIMIT') WHERE (SELECT COUNT(*) FROM assistants WHERE business_id=NEW.business_id)>=32
    OR COALESCE((SELECT SUM(length(CAST(id AS BLOB))+length(CAST(public_slug AS BLOB))+length(CAST(name AS BLOB))+length(CAST(greeting AS BLOB))+length(CAST(persona AS BLOB))+length(CAST(language AS BLOB))+length(CAST(voice AS BLOB))+length(CAST(custom_instructions AS BLOB))+length(CAST(engine AS BLOB))+length(CAST(realtime_model AS BLOB))+length(CAST(realtime_voice AS BLOB))+length(CAST(llm_model AS BLOB))) FROM assistants WHERE business_id=NEW.business_id),0)+length(CAST(NEW.id AS BLOB))+length(CAST(NEW.public_slug AS BLOB))+length(CAST(NEW.name AS BLOB))+length(CAST(NEW.greeting AS BLOB))+length(CAST(NEW.persona AS BLOB))+length(CAST(NEW.language AS BLOB))+length(CAST(NEW.voice AS BLOB))+length(CAST(NEW.custom_instructions AS BLOB))+length(CAST(NEW.engine AS BLOB))+length(CAST(NEW.realtime_model AS BLOB))+length(CAST(NEW.realtime_voice AS BLOB))+length(CAST(NEW.llm_model AS BLOB))>1048576;
  SELECT RAISE(ABORT,'OPENFON_ASSISTANT_WRITE_LIMIT') WHERE COALESCE((SELECT count FROM rate_counters WHERE bucket='assistants:'||NEW.business_id
    AND window_start=CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400),0)>=200;
  INSERT INTO rate_counters(bucket,window_start,count)
    VALUES('assistants:'||NEW.business_id,CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400,1)
    ON CONFLICT(bucket,window_start) DO UPDATE SET count=count+1;
END;
CREATE TRIGGER assistant_update_budget BEFORE UPDATE ON assistants BEGIN
  SELECT RAISE(ABORT,'OPENFON_ASSISTANT_WORKSPACE_CHANGE') WHERE NEW.business_id<>OLD.business_id;
  SELECT RAISE(ABORT,'OPENFON_ASSISTANT_STORAGE_LIMIT') WHERE length(CAST(NEW.id AS BLOB))+length(CAST(NEW.public_slug AS BLOB))+length(CAST(NEW.name AS BLOB))+length(CAST(NEW.greeting AS BLOB))+length(CAST(NEW.persona AS BLOB))+length(CAST(NEW.language AS BLOB))+length(CAST(NEW.voice AS BLOB))+length(CAST(NEW.custom_instructions AS BLOB))+length(CAST(NEW.engine AS BLOB))+length(CAST(NEW.realtime_model AS BLOB))+length(CAST(NEW.realtime_voice AS BLOB))+length(CAST(NEW.llm_model AS BLOB))>length(CAST(OLD.id AS BLOB))+length(CAST(OLD.public_slug AS BLOB))+length(CAST(OLD.name AS BLOB))+length(CAST(OLD.greeting AS BLOB))+length(CAST(OLD.persona AS BLOB))+length(CAST(OLD.language AS BLOB))+length(CAST(OLD.voice AS BLOB))+length(CAST(OLD.custom_instructions AS BLOB))+length(CAST(OLD.engine AS BLOB))+length(CAST(OLD.realtime_model AS BLOB))+length(CAST(OLD.realtime_voice AS BLOB))+length(CAST(OLD.llm_model AS BLOB))
    AND (SELECT SUM(length(CAST(id AS BLOB))+length(CAST(public_slug AS BLOB))+length(CAST(name AS BLOB))+length(CAST(greeting AS BLOB))+length(CAST(persona AS BLOB))+length(CAST(language AS BLOB))+length(CAST(voice AS BLOB))+length(CAST(custom_instructions AS BLOB))+length(CAST(engine AS BLOB))+length(CAST(realtime_model AS BLOB))+length(CAST(realtime_voice AS BLOB))+length(CAST(llm_model AS BLOB))) FROM assistants WHERE business_id=NEW.business_id)-(length(CAST(OLD.id AS BLOB))+length(CAST(OLD.public_slug AS BLOB))+length(CAST(OLD.name AS BLOB))+length(CAST(OLD.greeting AS BLOB))+length(CAST(OLD.persona AS BLOB))+length(CAST(OLD.language AS BLOB))+length(CAST(OLD.voice AS BLOB))+length(CAST(OLD.custom_instructions AS BLOB))+length(CAST(OLD.engine AS BLOB))+length(CAST(OLD.realtime_model AS BLOB))+length(CAST(OLD.realtime_voice AS BLOB))+length(CAST(OLD.llm_model AS BLOB)))+(length(CAST(NEW.id AS BLOB))+length(CAST(NEW.public_slug AS BLOB))+length(CAST(NEW.name AS BLOB))+length(CAST(NEW.greeting AS BLOB))+length(CAST(NEW.persona AS BLOB))+length(CAST(NEW.language AS BLOB))+length(CAST(NEW.voice AS BLOB))+length(CAST(NEW.custom_instructions AS BLOB))+length(CAST(NEW.engine AS BLOB))+length(CAST(NEW.realtime_model AS BLOB))+length(CAST(NEW.realtime_voice AS BLOB))+length(CAST(NEW.llm_model AS BLOB)))>1048576;
  SELECT RAISE(ABORT,'OPENFON_ASSISTANT_WRITE_LIMIT') WHERE COALESCE((SELECT count FROM rate_counters WHERE bucket='assistants:'||NEW.business_id
    AND window_start=CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400),0)>=200;
  INSERT INTO rate_counters(bucket,window_start,count)
    VALUES('assistants:'||NEW.business_id,CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400,1)
    ON CONFLICT(bucket,window_start) DO UPDATE SET count=count+1;
END;
