-- Bounds both compatibility tables; mirrored API saves consume two of 400 writes/day.
-- Historical rows remain removable/shrinkable. Refusals precede counter writes.
CREATE INDEX IF NOT EXISTS engine_profiles_budget_workspace ON engine_profiles(business_id);
CREATE TRIGGER engine_profiles_insert_budget BEFORE INSERT ON engine_profiles BEGIN
  
  SELECT RAISE(ABORT,'OPENFON_PRESET_STORAGE_LIMIT') WHERE (SELECT COUNT(*) FROM engine_profiles WHERE business_id=NEW.business_id)>=64 OR COALESCE((SELECT SUM(length(CAST(id AS BLOB))+length(CAST(name AS BLOB))+length(CAST(engine AS BLOB))+length(CAST(realtime_model AS BLOB))+length(CAST(realtime_voice AS BLOB))+length(CAST(language AS BLOB))+length(CAST(voice AS BLOB))+length(CAST(llm_model AS BLOB))+length(CAST(llm_base_url AS BLOB))+length(CAST(llm_api_key AS BLOB))) FROM engine_profiles WHERE business_id=NEW.business_id),0)+(length(CAST(NEW.id AS BLOB))+length(CAST(NEW.name AS BLOB))+length(CAST(NEW.engine AS BLOB))+length(CAST(NEW.realtime_model AS BLOB))+length(CAST(NEW.realtime_voice AS BLOB))+length(CAST(NEW.language AS BLOB))+length(CAST(NEW.voice AS BLOB))+length(CAST(NEW.llm_model AS BLOB))+length(CAST(NEW.llm_base_url AS BLOB))+length(CAST(NEW.llm_api_key AS BLOB)))>524288;
  SELECT RAISE(ABORT,'OPENFON_PRESET_WRITE_LIMIT') WHERE COALESCE((SELECT count FROM rate_counters WHERE bucket='presets:'||NEW.business_id
    AND window_start=CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400),0)>=400;
  INSERT INTO rate_counters(bucket,window_start,count) VALUES('presets:'||NEW.business_id,CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400,1)
    ON CONFLICT(bucket,window_start) DO UPDATE SET count=count+1;
END;
CREATE TRIGGER engine_profiles_update_budget BEFORE UPDATE ON engine_profiles BEGIN
  SELECT RAISE(ABORT,'OPENFON_PRESET_WORKSPACE_CHANGE') WHERE NEW.business_id<>OLD.business_id;
  SELECT RAISE(ABORT,'OPENFON_PRESET_STORAGE_LIMIT') WHERE (length(CAST(NEW.id AS BLOB))+length(CAST(NEW.name AS BLOB))+length(CAST(NEW.engine AS BLOB))+length(CAST(NEW.realtime_model AS BLOB))+length(CAST(NEW.realtime_voice AS BLOB))+length(CAST(NEW.language AS BLOB))+length(CAST(NEW.voice AS BLOB))+length(CAST(NEW.llm_model AS BLOB))+length(CAST(NEW.llm_base_url AS BLOB))+length(CAST(NEW.llm_api_key AS BLOB)))>(length(CAST(OLD.id AS BLOB))+length(CAST(OLD.name AS BLOB))+length(CAST(OLD.engine AS BLOB))+length(CAST(OLD.realtime_model AS BLOB))+length(CAST(OLD.realtime_voice AS BLOB))+length(CAST(OLD.language AS BLOB))+length(CAST(OLD.voice AS BLOB))+length(CAST(OLD.llm_model AS BLOB))+length(CAST(OLD.llm_base_url AS BLOB))+length(CAST(OLD.llm_api_key AS BLOB))) AND (SELECT SUM(length(CAST(id AS BLOB))+length(CAST(name AS BLOB))+length(CAST(engine AS BLOB))+length(CAST(realtime_model AS BLOB))+length(CAST(realtime_voice AS BLOB))+length(CAST(language AS BLOB))+length(CAST(voice AS BLOB))+length(CAST(llm_model AS BLOB))+length(CAST(llm_base_url AS BLOB))+length(CAST(llm_api_key AS BLOB))) FROM engine_profiles WHERE business_id=NEW.business_id)-(length(CAST(OLD.id AS BLOB))+length(CAST(OLD.name AS BLOB))+length(CAST(OLD.engine AS BLOB))+length(CAST(OLD.realtime_model AS BLOB))+length(CAST(OLD.realtime_voice AS BLOB))+length(CAST(OLD.language AS BLOB))+length(CAST(OLD.voice AS BLOB))+length(CAST(OLD.llm_model AS BLOB))+length(CAST(OLD.llm_base_url AS BLOB))+length(CAST(OLD.llm_api_key AS BLOB)))+(length(CAST(NEW.id AS BLOB))+length(CAST(NEW.name AS BLOB))+length(CAST(NEW.engine AS BLOB))+length(CAST(NEW.realtime_model AS BLOB))+length(CAST(NEW.realtime_voice AS BLOB))+length(CAST(NEW.language AS BLOB))+length(CAST(NEW.voice AS BLOB))+length(CAST(NEW.llm_model AS BLOB))+length(CAST(NEW.llm_base_url AS BLOB))+length(CAST(NEW.llm_api_key AS BLOB)))>524288;
  SELECT RAISE(ABORT,'OPENFON_PRESET_WRITE_LIMIT') WHERE COALESCE((SELECT count FROM rate_counters WHERE bucket='presets:'||NEW.business_id
    AND window_start=CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400),0)>=400;
  INSERT INTO rate_counters(bucket,window_start,count) VALUES('presets:'||NEW.business_id,CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400,1)
    ON CONFLICT(bucket,window_start) DO UPDATE SET count=count+1;
END;
CREATE INDEX IF NOT EXISTS engine_presets_budget_workspace ON engine_presets(business_id);
CREATE TRIGGER engine_presets_insert_budget BEFORE INSERT ON engine_presets BEGIN
  
  SELECT RAISE(ABORT,'OPENFON_PRESET_STORAGE_LIMIT') WHERE (SELECT COUNT(*) FROM engine_presets WHERE business_id=NEW.business_id)>=64 OR COALESCE((SELECT SUM(length(CAST(id AS BLOB))+length(CAST(name AS BLOB))+length(CAST(engine AS BLOB))+length(CAST(realtime_model AS BLOB))+length(CAST(realtime_voice AS BLOB))+length(CAST(language AS BLOB))+length(CAST(voice AS BLOB))+length(CAST(llm_model AS BLOB))) FROM engine_presets WHERE business_id=NEW.business_id),0)+(length(CAST(NEW.id AS BLOB))+length(CAST(NEW.name AS BLOB))+length(CAST(NEW.engine AS BLOB))+length(CAST(NEW.realtime_model AS BLOB))+length(CAST(NEW.realtime_voice AS BLOB))+length(CAST(NEW.language AS BLOB))+length(CAST(NEW.voice AS BLOB))+length(CAST(NEW.llm_model AS BLOB)))>524288;
  SELECT RAISE(ABORT,'OPENFON_PRESET_WRITE_LIMIT') WHERE COALESCE((SELECT count FROM rate_counters WHERE bucket='presets:'||NEW.business_id
    AND window_start=CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400),0)>=400;
  INSERT INTO rate_counters(bucket,window_start,count) VALUES('presets:'||NEW.business_id,CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400,1)
    ON CONFLICT(bucket,window_start) DO UPDATE SET count=count+1;
END;
CREATE TRIGGER engine_presets_update_budget BEFORE UPDATE ON engine_presets BEGIN
  SELECT RAISE(ABORT,'OPENFON_PRESET_WORKSPACE_CHANGE') WHERE NEW.business_id<>OLD.business_id;
  SELECT RAISE(ABORT,'OPENFON_PRESET_STORAGE_LIMIT') WHERE (length(CAST(NEW.id AS BLOB))+length(CAST(NEW.name AS BLOB))+length(CAST(NEW.engine AS BLOB))+length(CAST(NEW.realtime_model AS BLOB))+length(CAST(NEW.realtime_voice AS BLOB))+length(CAST(NEW.language AS BLOB))+length(CAST(NEW.voice AS BLOB))+length(CAST(NEW.llm_model AS BLOB)))>(length(CAST(OLD.id AS BLOB))+length(CAST(OLD.name AS BLOB))+length(CAST(OLD.engine AS BLOB))+length(CAST(OLD.realtime_model AS BLOB))+length(CAST(OLD.realtime_voice AS BLOB))+length(CAST(OLD.language AS BLOB))+length(CAST(OLD.voice AS BLOB))+length(CAST(OLD.llm_model AS BLOB))) AND (SELECT SUM(length(CAST(id AS BLOB))+length(CAST(name AS BLOB))+length(CAST(engine AS BLOB))+length(CAST(realtime_model AS BLOB))+length(CAST(realtime_voice AS BLOB))+length(CAST(language AS BLOB))+length(CAST(voice AS BLOB))+length(CAST(llm_model AS BLOB))) FROM engine_presets WHERE business_id=NEW.business_id)-(length(CAST(OLD.id AS BLOB))+length(CAST(OLD.name AS BLOB))+length(CAST(OLD.engine AS BLOB))+length(CAST(OLD.realtime_model AS BLOB))+length(CAST(OLD.realtime_voice AS BLOB))+length(CAST(OLD.language AS BLOB))+length(CAST(OLD.voice AS BLOB))+length(CAST(OLD.llm_model AS BLOB)))+(length(CAST(NEW.id AS BLOB))+length(CAST(NEW.name AS BLOB))+length(CAST(NEW.engine AS BLOB))+length(CAST(NEW.realtime_model AS BLOB))+length(CAST(NEW.realtime_voice AS BLOB))+length(CAST(NEW.language AS BLOB))+length(CAST(NEW.voice AS BLOB))+length(CAST(NEW.llm_model AS BLOB)))>524288;
  SELECT RAISE(ABORT,'OPENFON_PRESET_WRITE_LIMIT') WHERE COALESCE((SELECT count FROM rate_counters WHERE bucket='presets:'||NEW.business_id
    AND window_start=CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400),0)>=400;
  INSERT INTO rate_counters(bucket,window_start,count) VALUES('presets:'||NEW.business_id,CAST(strftime('%s',datetime('now')) AS INTEGER)/86400*86400,1)
    ON CONFLICT(bucket,window_start) DO UPDATE SET count=count+1;
END;
