import { test, expect } from './fixtures';
import { fillCatalog, expectCatalog } from './catalog-fields';

test('custom pipeline saves separate BYOK components and guided voices without exposing keys', async ({ page }) => {
  await page.goto('/auth');
  await page.getByLabel('Email').fill(`guided-${Date.now()}@example.invalid`);
  await page.getByLabel('Password', { exact: true }).fill('Synthetic-Presets-Password-1234');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await page.getByLabel('Business name', { exact: true }).fill('Guided voice workshop');
  await page.getByLabel('What do you do?').fill('Synthetic configuration validation');
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('button', { name: /Create.*assistant|Save.*assistant|Open.*studio/i }).click();
  await expect(page.getByRole('navigation', { name: 'Workspace' })).toBeVisible();
  await expect(page).toHaveURL('/overview');
  await page.goto('/settings');
  // The local instance is a custom provider; never suggest Kataleptic IDs for it.
  await expect(page.getByLabel('Workspace text model', { exact: true }).locator('option[value="llama-3.3-70b"]')).toHaveCount(0);
  await fillCatalog(page, 'Workspace text model', 'previous-custom-model');
  await page.getByLabel('Text provider preset', { exact: true }).selectOption('openai');
  await expect(page.getByLabel('Workspace text model', { exact: true })).toHaveValue('gpt-4.1-mini');
  await expect(page.getByLabel('Custom workspace text model', { exact: true })).toHaveCount(0);
  await page.getByLabel('Text API key', { exact: true }).fill('synthetic-text-private');
  await page.getByLabel('Transcription provider', { exact: true }).selectOption('openai');
  await page.getByLabel('Transcription API key', { exact: true }).fill('synthetic-stt-private');
  await page.getByLabel('Speech synthesis provider', { exact: true }).selectOption('azure');
  await expect(page.getByLabel('Speech synthesis base URL', { exact: true })).toHaveValue('');
  await page.getByLabel('Speech synthesis API key', { exact: true }).fill('synthetic-azure-key');
  await page.getByRole('button', { name: 'Save provider settings', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Speech URL');
  await page.getByLabel('Speech synthesis provider', { exact: true }).selectOption('openai');
  await expect(page.getByLabel('Speech synthesis model', { exact: true })).toHaveValue('gpt-4o-mini-tts');
  await page.getByLabel('Speech synthesis API key', { exact: true }).fill('synthetic-speech-private');
  await page.getByRole('button', { name: 'Save provider settings', exact: true }).click();
  await expect(page.getByText('Provider settings saved.', { exact: false })).toBeVisible();
  await page.reload();
  for (const name of ['Text','Transcription','Speech synthesis']) await expect(page.getByLabel(`${name} API key`, { exact: true })).toHaveValue('');
  const response = await page.request.get('/api/me/provider');
  const view = await response.json();
  expect(view).toMatchObject({ stt_provider: 'openai', tts_provider: 'openai', tts_api_key_configured: true });
  expect(JSON.stringify(view)).not.toContain('-private');
  const { assistants } = await (await page.request.get('/api/me/bootstrap')).json();
  const id = assistants[0].id;
  // Optional discovery failure must not discard successfully loaded provider settings.
  await page.route('**/api/me/provider/catalog', route => route.fulfill({ status: 503, json: { error: 'Synthetic catalog outage' } }));
  await page.goto(`/assistants/${id}`);
  await expect(page.getByText(/live Kataleptic catalog is temporarily unavailable/)).toBeVisible();
  await page.getByLabel('Conversation engine', { exact: true }).selectOption('pipeline');
  await page.getByLabel('Default language', { exact: true }).selectOption('de');
  await page.getByLabel('Speech voice', { exact: true }).selectOption('coral');
  await page.getByLabel('Language model', { exact: true }).selectOption('gpt-4o-mini');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByText('Assistant saved.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled();
  await page.reload();
  await expect(page.getByLabel('Conversation engine', { exact: true })).toHaveValue('pipeline');
  await expectCatalog(page, 'Speech voice', 'coral');
  await expectCatalog(page, 'Default language', 'de');
  await fillCatalog(page, 'Language model', 'future-custom-model');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByText('Assistant saved.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled();
  await page.reload();
  await expectCatalog(page, 'Language model', 'future-custom-model');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath('guided-pipeline-mobile.png'), fullPage: true });
  await page.goto('/settings');
  await expect(page.getByText('To remove the saved speech key, select Instance default or Browser speech, then save.')).toBeVisible();
  await page.getByLabel('Speech synthesis provider', { exact: true }).selectOption('browser');
  await page.getByRole('button', { name: 'Save provider settings', exact: true }).click();
  await expect(page.getByText('Provider settings saved.', { exact: false })).toBeVisible();
  expect(await (await page.request.get('/api/me/provider')).json()).toMatchObject({ tts_provider: 'browser', tts_api_key_configured: false });
});

test('guided Kataleptic tiers show matching voices and preserve unknown saved values', async ({ page }) => {
  // Isolated component data lets the UI inspect all families without paid calls.
  await page.goto('/auth');
  await page.getByLabel('Email').fill(`tiers-${Date.now()}@example.invalid`);
  await page.getByLabel('Password', { exact: true }).fill('Synthetic-Presets-Password-1234');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await page.getByLabel('Business name', { exact: true }).fill('Tier workshop');
  await page.getByLabel('What do you do?').fill('Synthetic configuration validation');
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('button', { name: /Create.*assistant|Save.*assistant|Open.*studio/i }).click();
  await expect(page.getByRole('navigation', { name: 'Workspace' })).toBeVisible();
  await expect(page).toHaveURL('/overview');
  const { assistants } = await (await page.request.get('/api/me/bootstrap')).json();
  await page.goto(`/assistants/${assistants[0].id}`);
  const engine = page.getByLabel('Conversation engine', { exact: true });
  await engine.selectOption('kataleptic-realtime');
  await page.getByLabel('Realtime voice', { exact: true }).selectOption('de_DE-thorsten-medium');
  await engine.selectOption('kataleptic-realtime-hd');
  await expectCatalog(page, 'Realtime voice', '');
  await page.getByLabel('Realtime voice', { exact: true }).selectOption('de-DE-SeraphinaMultilingualNeural');
  for (const model of ['gpt-realtime-2','gpt-realtime-2.1','gpt-realtime-2.1-mini']) {
    await engine.selectOption(model);
    await expect(page.getByLabel('Realtime voice', { exact: true })).toHaveValue('');
    await expect(page.getByLabel('Custom realtime voice', { exact: true })).toHaveCount(0);
    await page.getByLabel('Realtime voice', { exact: true }).selectOption('marin');
    await fillCatalog(page, 'Realtime voice', 'old-family-custom-voice');
    await expect(page.getByLabel('Speech voice', { exact: true })).toHaveCount(0);
    await expect(page.getByLabel('Summary language model', { exact: true })).toBeVisible();
  }
  await fillCatalog(page, 'Realtime voice', 'future-voice');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByText('Assistant saved.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled();
  await page.reload();
  await expectCatalog(page, 'Realtime voice', 'future-voice');
  await page.screenshot({ path: test.info().outputPath('guided-native-desktop.png'), fullPage: true });
});
